TRUNCATE TABLE dds_ksusha.skills_group RESTART IDENTITY CASCADE;
TRUNCATE TABLE dds_ksusha.skills RESTART IDENTITY CASCADE;
TRUNCATE TABLE dds_ksusha.levels RESTART IDENTITY CASCADE;
TRUNCATE TABLE dds_ksusha.departments RESTART IDENTITY CASCADE;
TRUNCATE TABLE dds_ksusha.positions RESTART IDENTITY CASCADE;
TRUNCATE TABLE dds_ksusha.employees RESTART IDENTITY CASCADE;
TRUNCATE TABLE dds_ksusha.skills_levels RESTART IDENTITY CASCADE;
TRUNCATE TABLE dds_ksusha.cv_dar RESTART IDENTITY CASCADE;