TRUNCATE TABLE dm_ksusha.now RESTART IDENTITY CASCADE;
TRUNCATE TABLE dm_ksusha.compare RESTART IDENTITY CASCADE;
TRUNCATE TABLE dm_ksusha.total_change RESTART IDENTITY CASCADE;
TRUNCATE TABLE dm_ksusha.complex_data RESTART IDENTITY CASCADE;
TRUNCATE TABLE dm_ksusha.employees_statistic RESTART IDENTITY CASCADE;