TRUNCATE TABLE dm2_ksusha.employees RESTART IDENTITY CASCADE;
TRUNCATE TABLE dm2_ksusha.departments RESTART IDENTITY CASCADE;
TRUNCATE TABLE dm2_ksusha.positions RESTART IDENTITY CASCADE;
TRUNCATE TABLE dm2_ksusha.skills_group RESTART IDENTITY CASCADE;
TRUNCATE TABLE dm2_ksusha.skills RESTART IDENTITY CASCADE;
TRUNCATE TABLE dm2_ksusha.levels RESTART IDENTITY CASCADE;
TRUNCATE TABLE dm2_ksusha.dep_data RESTART IDENTITY CASCADE;
TRUNCATE TABLE dm2_ksusha.departments_statistic RESTART IDENTITY CASCADE;

